# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_conditions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conditionfortesting',
            name='instance',
        ),
        migrations.DeleteModel(
            name='ConditionForTesting',
        ),
        migrations.DeleteModel(
            name='ModelForTesting',
        ),
    ]
